---
- name: Creatig a File
  hosts: all
  become: 'yes'
  become_method: sudo
  tasks:
    - name: Creating a Blank File in All App Servers
      file:
        path: /opt/appdata.txt
        state: touch
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0744'
