apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: testing-env
spec:
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /opt/mysql-db-volume
 
