apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: testing-env
spec:
  selector:
    app: mysql-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 3306
    nodePort: 30007