---
- name: Install a simple Apache web server on all app servers in Stratos DC. Also create a sample html page for now with some app specific data on it.
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: true
  tasks:
    
    - name: Create a File using blockin
      blockinfile:
        create: yes
        path: /root/facts.txt
        block: |
          Ansible managed node IP is {{ ansible_default_ipv4.address }}
  
    - name: Install httpd server on all app servers
      yum:
        name: httpd
        state: latest

    - name: copy file
      shell: cp /root/facts.txt /var/www/html/index.html

    - name: Start service httpd, if not started
      service:
        name: httpd
        state: started